services:
  - type: web
    name: gerros
    runtime: static
    buildCommand: pip install -r requirements.txt && python3 build.py
    staticPublishPath: public
    routes:
      - type: rewrite
        source: /privacy
        destination: /privacy.html
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=86400
